Repository he0119/CoolQBot, pull requests merged in 2024-07, with the labels that each got.

#596 feat: 使用 rye 管理项目
  .github/workflows/main.yml
  .gitignore
  .python-version
  Dockerfile
  README.md
  poetry.lock
  pyproject.toml
  requirements-dev.lock
  requirements.lock
  src/plugins/check_in/plugins/check_in_history.py
  src/utils/typing.py
Labels: enhancement, ci

#598 feat: 新增机器人健康检查 API
  CHANGELOG.md
  src/plugins/health_check.py
  tests/plugins/test_health.py
Labels: enhancement

#599 tests: 添加 Docker 运行测试
  .github/workflows/main.yml
  .python-version
  Dockerfile
  docker/start.sh
  pyproject.toml
  requirements-dev.lock
  requirements.lock
Labels: ci

#602 feat: 支持 QQ 机器人平台的校验文件
  CHANGELOG.md
  src/plugins/qq_bot.py
  tests/conftest.py
  tests/plugins/test_qq_bot.py
Labels: enhancement

#603 feat(ff14): 通过脚本更新 fflogs 的数据
  CHANGELOG.md
  pyproject.toml
  src/plugins/ff14/fflogs_data.json
  src/plugins/ff14/generate_fflogs_data.py
  src/plugins/ff14/plugins/ff14_fflogs/api.py
  src/plugins/ff14/plugins/ff14_fflogs/models.py
  tests/plugins/ff14/fflogs_data.json
  tests/plugins/ff14/test_fflogs.py
Labels: enhancement
